### ISSUE TITLE
Make clear that it doesn't specifically check the packages in pyproject.toml

### ISSUE THREAD

**Issue by rhtenhove** [sandrochuber/pylic#47]
This confused me at first, as I assumed `pylic` checks the `dependencies` listed in the `pyproject.toml`, although it only uses that file to configure itself. Then it checks _all_ installed packages, including any test packages such as `yamllint`, `pylint`, etc. if these are installed in the environment.

This could use some clarification to understand the output, as when running this without first installing all packages (using i.e. `pip install .`), it will say everything is fine, even though packages may be listed as dependencies which have problematic licenses.

**Comment by sandrochuber** [comment]
Hi @rhtenhove, thanks for creating the issue! Do you mean that the README is currently misleading? You could create a PR to improve it if you have time and passion :)

**Comment by rhtenhove** [comment]
Misleading is a bit much, just missing clarification which may cause wrong interpretation. I'll give a PR a go.
