### ISSUE TITLE
OSI Approved shown instead of actual license

### ISSUE THREAD

**Issue by rhtenhove** [sandrochuber/pylic#48]
Some packages, such as `sklearn` and our own package licensed under MPL-2.0, are shown as `OSI Approved`.

As this is a [long list](https://opensource.org/licenses/alphabetical) of licenses, we can't just accept this value. After searching I found https://pypi.org/project/pip-licenses/ which does show the correct license (for example `new BSD` for `sklearn`).

Are you interested in using their method of getting the license? As that may require some rework of the codebase, for which I won't have the time.

**Comment by sandrochuber** [comment]
Hi @rhtenhove, thanks for the issue! Indeed, this was not optimal. I added an extra case that handles these generic `OSI Approved` licenses, and should provide the more specific license instead. Some questions from my side: What's your package and can't you "just" put the specific classifier like `LICENSE :: OSI APPROVED :: MOZILLA PUBLIC LICENSE 2.0 (MPL 2.0)` (https://opensource.org/licenses/MPL-2.0)? It seems that also this is available on pypi so the metadata would fit: https://pypi.org/search/?c=License+%3A%3A+OSI+Approved+%3A%3A+Mozilla+Public+License+2.0+%28MPL+2.0%29

Does this help you?

**Comment by sandrochuber** [comment]
PS: I released version `1.2.3` which includes this improvement

**Comment by rhtenhove** [comment]
Excellent, thanks, just gave it a try and works like a charm!
Our main issue was the scikit-learn package, which showed OSI Approved but now shows new BSD. Now it also picks up our license as MPL-2.0, which is set in our `pyproject.toml` and which is correct.
Thanks!
